export const site = {
  name: "Rachat Bijoux Strasbourg",
  brandName: "Rachat Bijoux Strasbourg",
  legalName: "Rachat Bijoux Strasbourg — Maison Obagem",
  domain: "rachat-bijoux-strasbourg.site",
  url: "https://rachat-bijoux-strasbourg.site",
  city: "Strasbourg",
  citySlug: "strasbourg",
  postalCode: "67000",
  department: "Bas-Rhin (67)",
  region: "Grand Est (Alsace)",
  regionContext: "Strasbourg (67000) — Grande Île, Place Kléber, Petite France, Neustadt, Orangerie, Robertsau, Contades, Neudorf, Schiltigheim, Haguenau, Colmar et l'Alsace",
  tagline: "Cabinet d'Expertise Gemmologique & Rachat de Haute Joaillerie, Diamants et Montres de Prestige à Strasbourg",
  description: "Rachat Bijoux Strasbourg : Cabinet d'expertise gemmologique indépendante et rachat immédiat de diamants certifiés (GIA, HRD, SSEF) selon le cours officiel Rapaport, haute joaillerie signée (Cartier, Van Cleef & Arpels, Boucheron, Chaumet, Chopard, Bulgari), montres de collection (Rolex, Patek Philippe, Jaeger-LeCoultre, Omega, Cartier) et or d'investissement (lingots, pièces boursables, débris 18k). Salons privés confidentiels Place Kléber à Strasbourg et déplacements sécurisés dans tout le Bas-Rhin, Haut-Rhin et en Alsace. Virement bancaire instantané en EUR.",
  port: 3820,

  phone: "+33 1 48 87 81 44",
  phoneDisplay: "+33 1 48 87 81 44",
  phoneIntl: "+33148878144",
  whatsappPhone: "+33148878144",
  email: "contact@obagem.fr",
  whatsappUrl: "https://wa.me/33148872337",

  address: {
    street: "Place Kléber",
    postalCode: "67000",
    city: "Strasbourg",
    region: "Bas-Rhin",
    country: "FR",
    geo: { lat: 48.5834, lng: 7.7455 },
  },

  openingHours: [
    { day: "Lundi - Vendredi", hours: "09:30 - 19:00" },
    { day: "Samedi", hours: "10:00 - 18:00 (sur rendez-vous)" },
    { day: "Dimanche", hours: "Sur rendez-vous VIP" },
  ],

  stats: [
    { value: "40+", label: "Ans d'Expertise" },
    { value: "100%", label: "Virement Immédiat en EUR" },
    { value: "GIA / HRD", label: "Gemmologues Diplômés" },
    { value: "Rapaport", label: "Cours Mondial en Direct" },
  ],

  areasServed: [
    "Strasbourg",
    "Grande Île",
    "Place Kléber",
    "Place Broglie",
    "Petite France",
    "Neustadt",
    "Contades",
    "Orangerie",
    "Robertsau",
    "Neudorf",
    "Schiltigheim",
    "Bischheim",
    "Illkirch-Graffenstaden",
    "Haguenau",
    "Sélestat",
    "Colmar",
    "Mulhouse",
    "Bas-Rhin",
    "Alsace",
  ],
};
